examples2/django-online-store/cart/urls.py
from django.urls import path


from . views import (
    cart_add,
    cart_detail,
    cart_remove
)


app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

examples2/django-online-store/lenivastore/urls.py
from django.urls import include, path

from . import views


app_name = 'lenivastore'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('/<str:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', views.product_detail, name='product_detail'),
    path('about/', views.about_project, name='about_project'),
]

examples2/django-online-store/onstore/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views


urlpatterns = [
    path('', include('lenivastore.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examples2/django-online-store/lenivastore/models.py
import os
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True,
                            verbose_name="Название")
    slug = models.SlugField(max_length=100, unique=True)  # db_index=True
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновлен")

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('lenivastore:product_list_by_category', args=[self.slug])


def get_upload_path(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return os.path.join('images/', filename)


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products',
        verbose_name="Категория",
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True, verbose_name="Описание")  # Empty value
    features = models.TextField(blank=True, verbose_name="Характеристики")  # Empty value
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                verbose_name="Цена")
    available = models.BooleanField(default=True, verbose_name="Наличие")
    stock = models.PositiveIntegerField(verbose_name="Количество")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновлен")
    image = models.ImageField(upload_to=get_upload_path, blank=True,
                              verbose_name="Изображение товара")

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('lenivastore:product_detail', args=[self.id, self.slug])

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.brand_name)
    #     super(Brand, self).save(*args, **kwargs)

examples2/django-online-store/lenivastore/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q

from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    search_query = request.GET.get('search', '')

    if search_query:
        products = Product.objects.filter(
            Q(name__icontains=search_query) |
            Q(description__icontains=search_query))
        paginator = Paginator(products, len(products) or 100)
    else:
        paginator = Paginator(products, 12)

    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    is_paginated = page.has_other_pages()

    # if page.has_previous():
    #     prev_url = '?page={}'.format(page.previous_page_number())
    # else:
    #     prev_url = ''
    #
    # if page.has_next():
    #     next_url = '?page={}'.format(page.next_page_number())
    # else:
    #     next_url = ''

    context = {
        'page_object': page,
        'is_paginated': is_paginated,
        # 'next_url': next_url,
        # 'prev_url': prev_url,
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'lenivastore/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'lenivastore/product/detail.html', context)


def about_project(request):

    return render(request, 'lenivastore/product/about.html')

examples2/django-online-store/lenivastore/templates/lenivastore/product/about.html
{% extends 'lenivastore/base.html' %}

{% load static %}

{% block title %}
  About project
{% endblock %}

{% block content %}
  <div class="about_page">
    <h3 class="page_title">Об этом проекте</h3>
    <h4>
      Проект не является коммерческим (тоесть не оказывает услуг по продаже
      товаров), создан для освоения технологий разработки web-приложений.
    </h4>
    <div>
      <p>
        Проект является интеренет-магазином, предоставляющим товары. В данном
        случае электронику.
      </p>
      <p>
        Можно выбирать товары, добавлять в корзину, применять
        купоны на скидки, оформлять заказ. Оплата отключенна. После заказа
        присылается сообщение по электронной почте, с деталями заказа, а так же
        PDF файл. Реализованна регистрация и авторизация, профиль пользователя с
        возможностью просмотра заказов и изменением аватара пользователя.
      </p>
    </div>
    <div>
      <ul>
        <li>Проект создавался с помощью веб-фреймворка Django 2 (Python).</li>
        <li>
          Взаимодействие с базой данных осуществляется посредством механизма
          объектно-ориентированного отображения Django ORM.
        </li>
        <li>
          В качестве СУБД была использованна свободная объектно-реляционная СУБД
          PostgreSQL.
        </li>
        <li>
          Клиентская сторона пользовательского интерфейса написанна на HTML/CSS
          с использованием Flexbox и Grid CSS (Сайт адаптивный).
        </li>
        <li>
          На javascript написан всего один не большой скрипт.
        </li>
        <li>
          Система контроля версий Git.
        </li>
      </ul>
    </div>
  </div>
{% endblock %}

examples2/django-online-store/lenivastore/templates/lenivastore/product/detail.html
{% extends "lenivastore/base.html" %}

{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <h3 class="back_button">
    <a href="{{request.META.HTTP_REFERER}}">Назад</a>
  </h3>
  <div class="product_detail_wrapper">
    <h3>
      <a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}
      </a>
    </h3>
    <h2>{{ product.name }}</h2>
    <div class="product_img_desc_container">
      <div class="product_image_container">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}
        {% static 'images/no-image.jpeg' %}{% endif %}">
      </div>
      <div class="product_desc">
        <p>{{ product.description | linebreaks}}</p>
      </div>
    </div>
    <div class="product_content">
      <div class="price_forms">
        <h3 class="product_price">
          {{ product.price }} руб.
        </h3>
        <form class="product_detail_form" action="{% url 'cart:cart_add' product.id %}"
              method="post">
          {{ cart_product_form|join:"" }}
          {% csrf_token %}
          <input class="button_base blue_button" type="submit" value="Добавить в корзину">
        </form>
      </div>
      <h4>Характеристики</h4>
      <p>
        {{ product.features | linebreaks}}
      </p>
    </div>
  </div>
{% endblock %}

examples2/django-online-store/lenivastore/templates/lenivastore/product/list.html
{% extends 'lenivastore/base.html' %}

{% load static %}

{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}

{% block content %}
  <h3 class="page_title">
    {% if category %}{{ category.name }}{% else %}Товары{% endif %}
  </h3>
  <div class="card_list_wrapper">
    <div class="cards">
      {% for product in page_object.object_list %}
        <div class="card_item">
          <div class="card_image_container">
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}
              {% static 'images/no-image.jpeg'%}{% endif %}">
            </a>
          </div>
          <div class="card_content">
            <div class="card_title">
              <a class="text-medium" href="{{ product.get_absolute_url }}?next={{request.path}}">
                {{ product.name }}
              </a>
            </div>
          </div>
          <div class="card_info">
            <p class="card_price text-medium">{{ product.price }} руб.</p>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="pagination">
    {% if is_paginated %}
      {% if page_object.has_previous %}
        <a class="first_page" href="?page=1">Первая</a>
        <a class="prev_page" href="?page={{ page_object.previous_page_number }}">
          <i class="fa fa-angle-double-left" aria-hidden="true"></i>
        </a>
      {% endif %}

      {% for num in page_object.paginator.page_range %}
        {% if page_object.number == num %}
          <a class="nums_page selected_page" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_object.number|add:'-3' and num < page_object.number|add:'3' %}
          <a class="nums_page" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_object.has_next %}
        <a class="next_page" href="?page={{ page_object.next_page_number }}">
          <i class="fa fa-angle-double-right" aria-hidden="true"></i>
        </a>
        <a class="last_page" href="?page={{ page_object.paginator.num_pages }}">Последняя</a>
      {% endif %}
    {% endif %}
  </div>
{% endblock %}